language: python
#sudo: required

cache:
  directories:
    - $CACHE_DIR

services:
  - docker

before_install:
  - if [[ ! -d $CACHE_DIR ]] ; then echo "creating cached dir ${CACHE_DIR}"; mkdir -p ${CACHE_DIR}; fi
  - wget http://packages.confluent.io/archive/5.1/confluent-5.1.0-2.11.tar.gz
  - if [[ ! -f $CACHE_DIR/confluent-5.1.0-2.11.tar.gz ]] ; then echo "copying file to cache: ${CACHE_DIR}"; cp confluent-5.1.0-2.11.tar.gz ${CACHE_DIR}; fi
  - cp ${CACHE_DIR}/confluent-5.1.0-2.11.tar.gz .
  
#  - docker pull ikucan/pykafarr_build:1.0.0
#  - docker run ikucan/pykafarr_build:1.0.0

install:
  - echo `date` >> $CACHE_DIR/log.txt
  - cat $CACHE_DIR/log.txt
#  - pip install -r .requirements.txt
  
script:
 - cd $CACHE_DIR
 - pwd

matrix:
    include:
        - dist: xenail
          python: 3.7

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
