language: python
#sudo: required

services:
  - docker

before_install:
  - docker pull ikucan/pykafarr_build:1.0.0
  - docker run ikucan/pykafarr_build:1.0.0

install:
  - pip install -r .requirements.txt
  
script:
  - pwd

matrix:
    include:
        - dist: xenail
          python: 3.7
