language: python

before_install:
    - |
      if [[ $PYTHON && "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        python --version;
      fi;
i

install:
  - pip install -r .requirements.txt
  
script:
  - pwd
  - cd src
  - ls
  - type python
  - ./make.sh
  - echo "================= ${TRAVIS_OS_NAME} ==============="

matrix:
    include:
        - dist: xenial
          python: 3.7
