language: python
#sudo: required

cache:
  directories:
    - $CACHE_DIR

services:
  - docker

before_install:
  - if [[ ! -d $CACHE_DIR ]] ; then echo "creating cached dir ${CACHE_DIR}"; mkdir -p ${CACHE_DIR}; fi
  - wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3a%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fjdk8-downloads-2133151.html; oraclelicense=accept-securebackup-cookie;" "https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz"
#  - if [[ ! -f $CACHE_DIR/jdk.tgz ]] ; then echo "copying jdk file to cache: ${CACHE_DIR}"; mkdir -p ${CACHE_DIR}; fi
  
#  - docker pull ikucan/pykafarr_build:1.0.0
#  - docker run ikucan/pykafarr_build:1.0.0

install:
  - echo `date` >> $CACHE_DIR/log.txt
  - cat $CACHE_DIR/log.txt
#  - pip install -r .requirements.txt
  
script:
 - cd $CACHE_DIR
 - pwd

matrix:
    include:
        - dist: xenail
          python: 3.7

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
