language: python


before_install:
    - |
      if [[ $PYTHON && "$TRAVIS_OS_NAME" == "linux" ]]; then
        apt-get install librdkafka1
        apt-get install librdkafka-dev
        
      fi

install:
  - pip install -r .requirements.txt
  
script:
  - pwd
  - cd src
  - ls
  - type python
  - ./make.sh
  - echo "================= ${TRAVIS_OS_NAME} ==============="

matrix:
    include:
        - dist: xenial
          python: 3.7
