language: python
sudo: required

before_install:
    - |
      if [[ $PYTHON && "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install librdkafka1
        sudo apt-get install librdkafka-dev
        
      fi

install:
  - pip install -r .requirements.txt
  
script:
  - pwd
  - cd src
  - ls
  - type python
  - ./make.sh
  - ls /usr/include/librdkafka/

matrix:
    include:
        - dist: xenial
          python: 3.7
