language: python
sudo: required

before_install:
    - sudo apt-get install -yV librdkafka1
    - sudo apt-get install -yV librdkafka++1
    - sudo apt-get install -yV librdkafka-dev

install:
  - pip install -r .requirements.txt
  
script:
  - pwd
  - cd src
  - ls
  - type python
  - ./make.sh
  - ls -d /usr/include/lib*
  - ls /usr/include/librdkafka/

matrix:
    include:
        - dist: disco
          python: 3.7
