language: python
#sudo: required

#services:
#  - docker

install:
#  - docker pull ikucan/pykafarr_build:1.0.0
#  - docker pull ikucan/pykafarr_runtime:1.0.0

#script:
#  - docker run ikucan/pykafarr_build:1.0.0
  - test 1 -eq 1 

matrix:
    include:
        - name: "Docker contained build"
          dist: "xenail"
          python: "3.7"
 
