language: python
#sudo: required
cache:
  - $CACHE_DIR

services:
  - docker

before_install:
  - docker pull ikucan/pykafarr_build:1.0.0
  - docker run ikucan/pykafarr_build:1.0.0

install:
  - pip install -r .requirements.txt
  - echo `date` >> $CACHE_DIR/log
  - cat $CACHE_DIR/log
  
script:
  - pwd

matrix:
    include:
        - dist: xenail
          python: 3.7

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
