language: python
sudo: required

before_install:
#    ideally do this, but travis is only up to xenial (16.xx)
#    - sudo apt-get install -yV librdkafka1
#    - sudo apt-get install -yV 'librdkafka++1'
#    - sudo apt-get install -yV librdkafka-dev
    - sudo apt-get install -yV wget
    - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libr/librdkafka/librdkafka1_0.11.6-1.1_amd64.deb
    - ls -Fila
    - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libr/librdkafka/librdkafka++1_0.11.6-1.1_amd64.deb
    - ls -Fila
    - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libr/librdkafka/librdkafka-dev_0.11.6-1.1_amd64.deb
    - ls -Fila
    - sudo dpkg -i librdkafka1_0.11.6-1.1_amd64.deb
    - sudo dpkg -i librdkafka++1_0.11.6-1.1_amd64.deb
    - sudo dpkg -i librdkafka-dev_0.11.6-1.1_amd64.deb
    - dpkg-query -L librdkafka1
    - dpkg-query -L librdkafka++1
    - dpkg-query -L librdkafka-dev
    - rm librdkafka1_0.11.6-1.1_amd64.deb
    - rm librdkafka++1_0.11.6-1.1_amd64.deb
    - rm librdkafka-dev_0.11.6-1.1_amd64.deb
    - ./ubuntu-deps.sh

install:
  - pip install -r .requirements.txt
  
script:
  - pwd
  - cd src
  - ls
  - type python
  - ./make.sh
  - ls -d /usr/include/lib*
  - ls /usr/include/librdkafka/

matrix:
    include:
        - dist: xenail
          python: 3.7
