language: python
#sudo: required
cache:
  - $CACHE_DIR

services:
  - docker

#before_install:
#  - docker pull ikucan/pykafarr_build:1.0.0
#  - docker run ikucan/pykafarr_build:1.0.0

install:
  - if [[ -d $CACHE_DIR ] ; then echo "creating cached dir ${CACHE_DIR}"; mkdir -p ${CACHE_DIR}; fi
  - echo `date` >> $CACHE_DIR/log.txt
  - cat $CACHE_DIR/log.txt
#  - pip install -r .requirements.txt
  
script:
 - cd $CACHE_DIR
 - pwd

matrix:
    include:
        - dist: xenail
          python: 3.7

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
