package:
    name: pykafarr
    version: 0.7.0

source:
    path: ../src

build:
    include_recipe: False    
    number: 0
#    always_include_files:
#        - lib/libarrow*
#        - lib/libserdes*
#        - lib/libserdes*
#        - lib/libserdes*


requirements:
    build:
        - python
        - setuptools
        - numpy 1.15.4
        - pyarrow
        - cython
        - libboost

    run:
        - python
        - pyarrow
        - numpy 1.15.4
        - libboost
	
about:
    home: https://github.com/ikucan/pykafarr
    license: APACHE
